### PR TITLE
Changes for deploying infra and hosting artifacts outside US 

### PR DESCRIPTION
**Pull request by stevoscot92**
- Addition of cloudbuild bucket terraform module
- Addition of gcr domain terraform and environment variables
- Addition of gcs location var to gcs bucket creation command in setup script
- Boe_cre example run_demo.sh typo in dag file name 
- Addition of delete_contents_on_destroy var for BQ dataset tf module

### CODE REVIEW

**Comment by stevoscot92** [comment]
@mtronci above are changes I had to make in order to run the boe_cre example within my org that has organisational policies restricting deployment of resources in US.

**Comment by mescanne** [comment]
A few questions about this -

- It looks like you're creating two buckets -- as you added the "Create cloudbuild GCS bucket" terraform -- using the ../modules/cloud_storage. This is then exposed as an output. Why not stick to the GCS bucket created in the "gcs_buckets" module? Did that not work for you?
- gcr_hostname being a variable is a great idea and is useful. I also have been wanting to use our Artifact Repository, instead, and this is a step forward. REPO_HOSTNAME may be better but that is less important. (So it can be GCR or the Artifact Repository)
- Setting location of the Terraform bucket is really good.

I think it looks good -- it's just the first question that's of interest. The ingest-data bucket *should* already be created in the right region, but wasn't working?

Thanks,
Mark

**Comment by stevoscot92** [comment]
@mescanne thank you for the feedback. Regarding the first question, the ingest bucket was created successfully using the terraform-google-cloud-storage module. However, the additional local GCS bucket module cloudbuild_gcs_bucket was used to create a dummy cloud build source staging bucket. This was because of the requirement described [here](https://cloud.google.com/sdk/gcloud/reference/builds/submit#--gcs-source-staging-dir). If no cloud build source staging bucket exists then cloud build creates one in US multi-region. My initial method was clumsy so I have made some changes as per latest commit [a96df591854f0357f1e3032ec57383a7969c6b31](https://github.com/GoogleCloudPlatform/reg-reporting-blueprint/pull/20/commits/a96df591854f0357f1e3032ec57383a7969c6b31) .

**Comment by stevoscot92** [comment]
@mescanne I have just added the region flag with the region env var to the gcloud build submit command across the examples, as per below commit. Thanks! 

https://github.com/GoogleCloudPlatform/reg-reporting-blueprint/pull/20/commits/942458393e47a955f44d4d7ad8905a708223fd03

**Review by mescanne — APPROVED** [review]
@stevoscot92 Thanks a lot for this PR -- very much appreciated!

I'm happy to merge it as-is -- one question, though. If you'd like, you can add your name to the AUTHORS file. It is not necessary, as the commit history will always have your name on it.

Mark

**Comment by stevoscot92** [comment]
@mescanne please merge as-is.

Thanks!
Steve

**Pull request merged**
